import React, { useMemo, useState } from 'react'
import { activeCases } from '../../data/dashboardData'
import { Badge, DetailPanel, FilterBar, Page, Toast } from '../../components/shared/UI'

export default function ActiveCases() {
  const [filters, setFilters] = useState({ priority: 'All', status: 'All', city: 'All', query: '' })
  const [selected, setSelected] = useState(null); const [toast, setToast] = useState('')
  const update = (key, value) => setFilters({ ...filters, [key]: value })
  const cases = useMemo(() => activeCases.filter(c => (filters.priority === 'All' || c.priority === filters.priority) && (filters.status === 'All' || c.status === filters.status) && (filters.city === 'All' || c.city === filters.city) && `${c.id} ${c.complainant}`.toLowerCase().includes(filters.query.toLowerCase())), [filters])
  const action = label => { setToast(`${label} queued for officer review`); setTimeout(() => setToast(''), 2200) }
  return <Page title="Active Cases" subtitle="Prioritised complaints requiring investigation">
    <FilterBar><input placeholder="Search case or complainant" value={filters.query} onChange={e => update('query', e.target.value)} />{[['priority',['All','Critical','High','Medium','Low']],['status',['All','Investigating','Pending','Escalated']],['city',['All',...new Set(activeCases.map(c=>c.city))]]].map(([key, vals]) => <select key={key} value={filters[key]} onChange={e => update(key,e.target.value)}>{vals.map(v=><option key={v}>{v}</option>)}</select>)}</FilterBar>
    <div className="card table-wrap"><table><thead><tr><th>Case ID</th><th>Complainant</th><th>Amount</th><th>Bank / City</th><th>Incident</th><th>Priority</th><th>Status</th><th>Filed</th></tr></thead><tbody>{cases.map(c=><tr key={c.id} onClick={()=>setSelected(c)}><td><strong>{c.id}</strong></td><td>{c.complainant}</td><td>₹{c.amount.toLocaleString('en-IN')}</td><td>{c.bank}<br/><small>{c.city}</small></td><td>{c.incidentType}</td><td><Badge value={c.priority}/></td><td><span className="status-pill">{c.status}</span></td><td>{c.filedTime}</td></tr>)}</tbody></table></div>
    {selected && <DetailPanel title={`${selected.id} · Case detail`} onClose={()=>setSelected(null)}><Badge value={selected.priority}/><p className="detail-summary">{selected.summary}</p><div className="detail-grid"><div><b>Transaction</b><span>₹{selected.amount.toLocaleString('en-IN')} · {selected.bank}<br/>{selected.account}</span></div><div><b>Last known caller location</b><span>Placeholder: cell-tower trace pending</span></div><div><b>Assigned officer</b><span>{selected.officer}</span></div><div><b>Mule-account chain</b><span>Victim → M-1008 → M-1009 → beneficiary</span></div></div><h4>Status timeline</h4><ul className="timeline"><li><b>Filed</b> · {selected.filedTime}</li><li><b>Investigation assigned</b> · 23 Sep 2026, 18:50</li><li><b>Current</b> · {selected.status}</li></ul><div className="button-row"><button onClick={()=>action('Escalation')}>Escalate</button><button onClick={()=>action('Freeze request')}>Freeze linked account</button><button onClick={()=>action('Legal notice')}>Generate legal notice</button></div></DetailPanel>}<Toast text={toast}/></Page>
}
